# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iPark-Admin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iPark-Admin

pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Firestore'

  target 'iPark-AdminTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iPark-AdminUITests' do
    # Pods for testing
  end

end
